### PR TITLE
Meme flags

### LINKED ISSUE #69: Meme-flags not working
The API changed recently on how those are handled (https://github.com/4chan/4chan-API/commit/d095a7af76d0a5a48e3008fb9a05e5b3bbb6c2bb#diff-56f89e7e247c69b9ea157a734f34db02eec464c520f2f8620e1541cd5faec37a), the text-only implementation is atm broken on /mlp/ and partially on /pol/
Have a WIP implementation which uses the gifs, will try to create a PR a bit later today

### PR DESCRIPTION
**Pull request by szopin**
Graphical flags implementation with meme-flag support (should close #69 hopefully). Not sure if it will look good on higher res devices, looks ok on a jollaC. 
Works 99% of the time, not sure why but if OP is using a meme flag it is not displayed (like with the 'undefined' from text implementation), ~~all other posts after first do work~~, not really sure why, I guess there is some threading after first post, but no idea why it doesn't capture board_flag (works fine with the country/countrycode)
edit: Actually just found an example of two first posts in a thread not displaying, so it looks like board_flag is undefined until first real flag comes around?? Really not sure what's happening

### CODE REVIEW

**Comment by tabasku** [comment]
Seems to look fine on Xperia X. Did not encounter missing posts though while testing

**Review by tabasku — APPROVED** [review]

**Comment by szopin** [comment]
It's just flags missing on /pol/ if the first few posters use board_flags, seems to work fine on /mlp/ (mix of country/country_name + board_flag/flag_name seems like the culprit) really weird

On Saturday, 29 May 2021, tabasku wrote:
> Seems to look fine on Xperia X. Did not encounter missing posts though while testing
> 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/tabasku/harbour-neliapila/pull/70#issuecomment-85081563

-- 
Sent from my Jolla

**Comment by szopin** [comment]
Example of board_flags used in OP:
/mlp/ - works and displays fine: https://a.4cdn.org/mlp/thread/37054586.json
/pol/ - first two posts by OP don't display the flag, third one (after normal flag Romania posted) works: https://a.4cdn.org/pol/thread/323708054.json
all json elements look the same, some kind of black magic

**Comment by szopin** [comment]
Screenshot-21-06-02-17-42-51
it's even weirder as meme flags do work until clash with country flags, wth

**Comment by tabasku** [comment]
Well, I would say its not really blocker though :) I think we could update this with 0.7 to openrepos / harbour

**Comment by szopin** [comment]
Oh yeah, it works more than 99% of the time, bant/int/mlp all work fine 100% and 99% of /pol/ too (luckily memeflags are rare and even in memeflag thread only 1-2 first posts are impacted and it starts magically working, so 1-2/300 if a thread lives), I am burnt out from testing /mlp/ and /pol/ anyway, do plan to make a 'show posts by ID' feature once IDs and flags are in (filter out memeflag posters?)

**Pull request merged**
